project:
  type: website

execute:
  freeze: auto

website:
  title: "LT-GEE Lessons and Resources"
  site-url: https://cafri-labs.github.io/lt_user_guide/
  repo-url: hhttps://github.com/cafri-labs/lt_for_femc
  repo-actions: [edit,issue]
  reader-mode: true
  page-navigation: true
  sidebar:
    style: docked
    search: true
    contents:
     - index.qmd
     - getting_started.qmd
     - tuning.qmd
     - timesync.qmd

format:
  html:
    theme: cosmo
    toc: true

